const EError = {
    ROUTING_ERROR:1,
    VALIDATION_ERROR:2,
    AUTHENTICATION_ERROR:3,
    AUTHORIZATION_ERROR:4,
    INTERNAL_SERVER_ERROR:5,
    NOT_FOUND_ERROR:6,
    BAD_REQUEST_ERROR:7,
    FORBIDDEN_ERROR:8,
    INVALID_TYPE_ERROR:9,
    DATABASE_ERROR:10,
    DOCUMENTATION_ERROR:11,
    GENERIC_ERROR: 999
}

export default EError;